# Generated by Django 5.1.6 on 2025-03-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.IntegerField(default=0)),
                ('card_name', models.IntegerField(default=0)),
                ('card_cvc', models.IntegerField(default=0)),
                ('card_exp', models.IntegerField(default=0)),
            ],
        ),
    ]
