# Generated by Django 5.1.6 on 2025-03-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='card_cvc',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='payments',
            name='card_exp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='card_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='card_num',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
