# Generated by Django 5.1.6 on 2025-03-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_payments_card_cvc_alter_payments_card_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='card_name',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
