# Generated by Django 5.1.6 on 2025-03-06 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_payments_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='card_cvc',
            field=models.CharField(blank=True, max_length=3, validators=[django.core.validators.MinLengthValidator(3, message='CVC has to be 3 digits')]),
        ),
        migrations.AlterField(
            model_name='payments',
            name='card_num',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.MinLengthValidator(16, message='Card Number Must be 16 digits.')]),
        ),
    ]
