# Generated by Django 5.1.6 on 2025-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_payments_card_cvc_alter_payments_card_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_flight',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
